# Generated by Django 3.1 on 2020-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='interested_things',
        ),
        migrations.RemoveField(
            model_name='web',
            name='subject',
        ),
        migrations.AddField(
            model_name='web',
            name='receiveage',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='web',
            name='relationship',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='web',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='web',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
