# Generated by Django 3.1 on 2020-09-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200910_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='web',
            name='receivername',
            field=models.CharField(default='', max_length=30),
        ),
    ]
